tests/Propel/Tests/Runtime/ActiveQuery/ExistsTest.php

Fixes broken tests. Apparently, the order of retrieved objects has to be set, which makes sense. Curious though that the problem only started to appear just recently and only with Postgres on PHP 8.2.

fix broken test on Postgres with PHP 8.2

---

src/Propel/Generator/Builder/Om/ObjectBuilder.php
src/Propel/Runtime/Util/UuidConverter.php
tests/Fixtures/bookstore/schema.xml
tests/Propel/Tests/Runtime/TypeTests/UuidBinaryTypeTest.php
tests/Propel/Tests/Runtime/Util/UuidConverterTest.php

Fixes https://github.com/propelorm/Propel2/issues/1914#issuecomment-1740411522.
I have also changed the UuidConverter, so that it handles null values. The initial idea was to be strict with the type, but it is not robust and lead to ugly code, where the null check has to be performed manually every time.

Convert UUID_BINARY in PK during update

---

src/Propel/Generator/Builder/Om/TableMapBuilder.php
src/Propel/Generator/Model/Column.php
tests/Propel/Tests/Generator/Model/InheritanceTest.php

When using [single table inheritance](https://propelorm.org/documentation/08-inheritance.html#single-table-inheritance), the keys for the individual classes are written to the TableMap as constants. Those are used during instantiation of the subclasses.
For example, an inheritance declaration like
```xml
<column name="type_indicator"  inheritance="single">
<inheritance key="firstClassIdentifier" class="..." extends="..."/>
</column>
```
will create a constant in the TableMap:
```php
public const CLASSKEY_FIRSTCLASSIDENTIFIER = 'firstClassIdentifier';
```
and a constructor of the subclass:
```php
public function __construct()
{
parent::__construct();
$this->setTypeIndicator(FooTableMap::CLASSKEY_FIRSTCLASSIDENTIFIER);
}
``` 
The value of the classkey constant is always written as a string, …

Fix single table inheritance classkey type

---

tests/Propel/Tests/Generator/Behavior/OutputGroup/OutputGroupBehaviorTest.php

Allows declaring output groups on columns and foreign key relations in schema.xml. Passing a group name to the `toOutputGroup()` method on the model or ObjectCollection returns an array holding all values defined by the group name.
Declare groups in schema.xml:
```xml
<table name="le_table">
<column name="col1" outputGroup="foo,bar" />
<column name="col2" />
<foreign-key phpName="fk" outputGroup="foo">
...
```
Serialize objects by output group:
```php
leTableObject->toOutputGroup('foo'); // will return ['Col1' => ..., 'Fk' => ...]
leTableObject->toOutputGroup('bar'); // will return ['Col1' => ...]
```
Instead of a group name, an array with model class names can also be used. In this form, multiple groups can be given in an array:
```php
leTableObject->toOutputGroup([
LeTable::class => …
```

add output groups behavior

---

src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorQueryBuilderModifier.php
src/Propel/Generator/Builder/Om/ObjectBuilder.php
src/Propel/Runtime/ActiveQuery/ModelCriteria.php
src/Propel/Runtime/Formatter/StatementFormatter.php
src/Propel/Runtime/Map/TableMapTrait.php
templates/Builder/Om/baseObjectAttributes.php
templates/Builder/Om/baseObjectMethods.php
tests/Propel/Tests/Generator/Builder/Om/GeneratedObjectRelTest.php

fixes some errors when running linters on generated model files:
- fixed some doctypes
- removed yoda expressions
- some cleanup

object code generator cleanup

---

tests/Fixtures/bookstore/schema.xml
tests/Fixtures/schemas/schema.xml

Fixes error when running the test with MySQL 8.4 (latest):
```
In SqlManager.php line 203:
SQL insert failed: CREATE TABLE `contest`.`bookstore_contest_entry`     
(                                                                       
`bookstore_id` INTEGER NOT NULL,                                    
`contest_id` INTEGER NOT NULL,                                      
`customer_id` INTEGER NOT NULL,                                     
`entry_date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,              
PRIMARY KEY (`bookstore_id`,`contest_id`,`customer_id`),            
INDEX `bookstore_contest_entry_fi_6043da` (`customer_id`),          
CONSTRAINT `bookstore_contest_entry_fk_2e7157`                      
FOREIGN KEY (`bookstore_id`)                                    
REFERENCES …
```

fix test schemas: mysql requires unique index for complex fk

---

src/Propel/Generator/Builder/Om/ObjectBuilder.php
src/Propel/Generator/Model/Domain.php
src/Propel/Generator/Model/PropelTypes.php
templates/Behavior/Validate/objectAttributes.php
tests/Propel/Tests/Generator/Model/ColumnTest.php

Some doctypes are generated with PHP type `boolean`:
```
* @method     ChildUser[]|Collection findByIsDeleted(boolean|array<boolean> $is_deleted) Return ChildUser objects filtered by the is_deleted column
``` 
But it should be `bool`.

replace php type boolean with bool

---

.github/workflows/ci.yml

Github CI requires actions/cache at v4, see [announcement](https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down).
Update is straight-forward, just update the version number.

update github ci to use actions/cache v4

---

tests/bootstrap.php

Set env variable `ALLOW_TESTS_AS_ROOT` to run propel tests as root. Makes it easier to run tests in a docker container.

allow running propel tests as root

---

.github/workflows/ci.yml
tests/Propel/Tests/Helpers/Bookstore/BookstoreTestBase.php
tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php
tests/Propel/Tests/Runtime/Formatter/ArrayFormatterWithTest.php

sqlite tests are failing for no apparent reason 
> PDOException: SQLSTATE[HY000]: General error: 5 database is locked
(see failed job [here](https://github.com/mringler/Propel2/actions/runs/13856140809/job/38773291017))
Might be an issue with the sqlite version? Updating to more recent Ubuntu version can't hurt either way.

switch ci to ubuntu 24.04 and minor fixes

---

src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
src/Propel/Runtime/ActiveQuery/Criteria.php
src/Propel/Runtime/ActiveQuery/ModelCriteria.php
src/Propel/Runtime/ActiveQuery/SqlBuilder/AbstractSqlQueryBuilder.php
src/Propel/Runtime/ActiveQuery/SqlBuilder/SelectQuerySqlBuilder.php
src/Propel/Runtime/ActiveQuery/Util/ColumnResolver.php
src/Propel/Runtime/ActiveQuery/Util/ResolvedColumn.php
tests/Propel/Tests/Runtime/ActiveQuery/CriteriaReplaceNameTest.php

Clean up column resolve in Model(Criteria).
Mostly extracts these methods into a new utility class:
- `Criteria::replaceNames()`: normalizes column name literals in strings AND extracts column map for found columns
- `ModelCriteria::doReplaceNameInExpression()`: preg callback used in Criteria::replaceNames() (!)
- `ModelCriteria::getColumnFromName()`: find column map for a column string.
- `ModelCriteria::getColumnFromSubQuery()`: utility function used in ModelCriteria::getColumnFromName()
Original has issues with inheritance, where parent class (Criteria) uses properties and calls methods only available on child class (ModelCriteria). Also, Criteria had class attributes to transfer data from a callback (`replacedColumns`, `currentAlias`, `foundMatch`) back to caller.
Class attributes …

Extract column replacement out of (Model)Criteria

---

src/Propel/Runtime/ActiveQuery/Criteria.php
src/Propel/Runtime/ActiveQuery/ModelCriteria.php
src/Propel/Runtime/ActiveQuery/SqlBuilder/SelectQuerySqlBuilder.php
src/Propel/Runtime/Adapter/Pdo/PdoAdapter.php
tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php
tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
tests/Propel/Tests/Runtime/ActiveQuery/SubQueryTest.php
tests/Propel/Tests/Runtime/Adapter/AbstractAdapterTest.php

Previous change added tables found in AS columns to FROM clause, same as with SELECT columns.
This leads to tables from subquery end up in FROM, i.e.:
```php
$colDef = <<< EOF
CASE WHEN EXISTS(
SELECT 1
FROM author
WHERE author.id = book.author_id
)
THEN 1 ELSE 0 END
EOF;
$actual = BookQuery::create()->addAsColumn('hasAuthor', $colDef)
```
will have a cross join to `author` in FROM clause.
This restores old behavior, so no tables from AS columns will be added to FROM (same should apply to SELECT).
<hr>
Previous change also always added table from ModelCriteria to FROM, whereas before it had to be used in SELECT or WHERE, which (I think) catered to a very specific use-case (use ModelQuery as proxy for subquery with the same ModelQuery), but causes weird behavior when using only AS columns, …

do not add tables from AS columns

---

src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifier.php
src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorQueryBuilderModifier.php
src/Propel/Generator/Behavior/Sluggable/SluggableBehavior.php
src/Propel/Generator/Behavior/Sortable/SortableBehaviorQueryBuilderModifier.php
src/Propel/Generator/Behavior/Timestampable/TimestampableBehavior.php
src/Propel/Generator/Behavior/Versionable/VersionableBehaviorQueryBuilderModifier.php
src/Propel/Generator/Builder/Om/ObjectBuilder.php
src/Propel/Generator/Builder/Om/QueryBuilder.php
src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
src/Propel/Runtime/ActiveQuery/ColumnResolver/ColumnExpression/LocalColumnExpression.php
src/Propel/Runtime/ActiveQuery/Criteria.php
src/Propel/Runtime/ActiveQuery/DeprecatedCriteriaMethods.php
src/Propel/Runtime/ActiveQuery/JoinBuilder.php
src/Propel/Runtime/ActiveQuery/ModelCriteria.php
src/Propel/Runtime/ActiveQuery/ModelJoin.php
src/Propel/Runtime/ActiveQuery/QueryExecutor/InsertQueryExecutor.php
tests/Propel/Tests/Runtime/ActiveQuery/CriteriaIsEmptyTest.php
tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php
tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaTest.php
tests/Propel/Tests/Runtime/Util/TableMapExceptionsTest.php

Removes old Criteria/ModelCriteria methods. The methods are put into a new class and are called from there via magic `__call` with a deprecation warning.
Main reasons for deprecation are:
- method likely intended for internal use only, but is not used
- confusing name
-  deprecated or unimplemented functionality 
| method | reason for deprecation | replace with |
|---|---|---|
| getMap() | `map` was split into `updateValues` and `filterCollector` | `getUpdateValues()` or `getFilterCollector()` |
| keys() | naming, no more map | use `array_keys()` on  `getUpdateValues()` or `getFilterCollector()` |
| containsKey() | checks if `map` has an update value | `hasUpdateValue()` |
| keyContainsValue() | checks if update value is actually a value | `getUpdateValue() === null` |
| getCriterion() | …

externalize deprecated Criteria interface

---

src/Propel/Runtime/ActiveQuery/ModelCriteria.php
templates/Builder/Om/baseQueryClassHeader.php
tests/Propel/Tests/Runtime/ActiveQuery/ModelCriteriaFormatterTest.php

Adds typed `find()` methods to query objects.
```php
$books = BookQuery::create()->findObjects(); // returns ObjectCollection<Book>
$book = $books->get(1); // will be Book
$books = BookQuery::create()->findTuples(); // returns ArrayCollection
$book = $books->get(1); // will be array<string, mixed>
```

add typed find() methods

---

psalm.xml
src/Propel/Generator/Builder/Om/ExtensionQueryBuilder.php
src/Propel/Generator/Builder/Om/QueryBuilder.php
src/Propel/Runtime/ActiveQuery/BaseModelCriteria.php
src/Propel/Runtime/ActiveQuery/ModelCriteria.php
src/Propel/Runtime/ActiveQuery/TypedModelCriteria.php
templates/Builder/Om/baseQueryClassHeader.php
templates/Builder/Om/baseQueryExistsMethods.php
templates/Builder/Om/baseQueryInMethods.php
tests/Propel/Tests/Generator/Util/QuickBuilderTest.php

Allows to restore parent query type after `endUse()`:
```php
$b = BookQuery::create();                              // BookQuery<null>
$b = $b->useAuthorQuery();                             // AuthorQuery<BookQuery<null>>
$b = $b->useEssayRelatedByFirstAuthorIdExistsQuery();  // EssayQuery<AuthorQuery<BookQuery<null>>>
$b = $b->endUse();                                     // AuthorQuery<BookQuery<null>>
$b = $b->endUse();                                     // BookQuery<null>
```
A generic parameter is added through a new child class of ModelCriteria (`TypedModelCriteria`) which is set as parent class to the query classes. The current class is set as type parameter to the class returned by `useXXXQuery()` and unwrapped on `endUse()`.
Extending ModelCriteria and adding a type parameter to …

Restore parent query type after endUse()

---

README.md
src/Propel/Generator/Builder/Om/TableMapBuilder.php
src/Propel/Runtime/ActiveQuery/QueryExecutor/DeleteQueryExecutor.php
tests/Propel/Tests/BookstoreTest.php
tests/Propel/Tests/Generator/Builder/Om/GeneratedQueryDoDeleteTest.php
tests/Propel/Tests/Helpers/Bookstore/BookstoreTestBase.php
tests/Propel/Tests/Runtime/Util/TableMapExceptionsTest.php
tests/Propel/Tests/Runtime/Util/TableMapTest.php
tests/Propel/Tests/TestCase.php

Propel Criteria allows to delete from multiple tables in the same Criteria:
```php
$c = new Criteria();
$c->add(BookTableMap::COL_ID, $hp->getId());
$c->add(AuthorTableMap::COL_ID, $hp->getAuthorId());
$c->add(PublisherTableMap::COL_ID, $hp->getPublisherId());
BookTableMap::doDelete($c);
```
This has several down-sides:
- creates inconsistent state when objects in pools are not cleared
- relies on resolving table names from filters, which is not 100% reliable
- like reusing the same variable multiple times with different types and meaning
- doesn't seem to be documented behavior
I see literally no upside to this.
This PR removes multi-table deletes.

No multitable delete

---

src/Propel/Generator/Behavior/AggregateColumn/AggregateColumnRelationBehavior.php
src/Propel/Generator/Behavior/Delegate/DelegateBehavior.php
src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorObjectBuilderModifier.php
src/Propel/Generator/Behavior/NestedSet/NestedSetBehaviorQueryBuilderModifier.php
src/Propel/Generator/Behavior/Sortable/SortableBehaviorQueryBuilderModifier.php
src/Propel/Generator/Builder/Om/AbstractOMBuilder.php
src/Propel/Generator/Builder/Om/ObjectBuilder.php
src/Propel/Generator/Builder/Om/QueryBuilder.php
templates/Behavior/Validate/objectValidate.php

see propelorm/Propel2#2019
requested and explained in #38

Mark nullable parameters as such in generated code

---

src/Propel/Runtime/ActiveQuery/Criteria.php
src/Propel/Runtime/ActiveQuery/Criterion/AbstractCriterion.php
src/Propel/Runtime/ActiveQuery/DeprecatedCriteriaMethods.php
src/Propel/Runtime/ActiveQuery/FilterExpression/AbstractColumnFilter.php
src/Propel/Runtime/ActiveQuery/FilterExpression/AbstractFilterClauseLiteral.php
src/Propel/Runtime/ActiveQuery/FilterExpression/AbstractInnerQueryFilter.php
src/Propel/Runtime/ActiveQuery/FilterExpression/BinaryColumnFilter.php
src/Propel/Runtime/ActiveQuery/FilterExpression/ColumnFilterInterface.php
src/Propel/Runtime/ActiveQuery/FilterExpression/FilterCollector.php
src/Propel/Runtime/ActiveQuery/FilterExpression/InColumnFilter.php
src/Propel/Runtime/ActiveQuery/FilterExpression/LikeColumnFilter.php
tests/Propel/Tests/Runtime/ActiveQuery/CriteriaTest.php

Filter::getLocalColumnName() had a default value that was not consistent across child classes. There should not be a default value on a method like this.
Additional fix for #42

Filter::getLocalColumnName(): no more default value

---

composer.json

The `replace' statements in composer.json regarding symfony/polyfill break projects that depend on those packages.
PR removes those statements.
Reported in [review discussion](https://github.com/mringler/perpl/pull/49#discussion_r2068190415) by @rvanvelzen (thank you!).

remove symfony/polyfill replacements

---

src/Propel/Generator/Behavior/Timestampable/TimestampableBehavior.php
tests/Propel/Tests/Generator/Behavior/Timestampable/TimestampableBehaviorTest.php

@mringler like you mentioned earlier:
the Timestampable behavior generated 1 or 2 unused variables (depending on schema configuration).
This takes care of those.
It also adds 2 tests which are in Propel2 by now.

avoid declaring unused variables in timestampable behavoir
